spring:
  mvc:
    static-path-pattern: /static/**

    resources:
      static-locations: classpath:/static/

server:
  servlet:
    session:
      cookie:
        max-age: 86400s                # 设置session cookie 的过期时间
